[ATK]
[ATK.id-atk-0000]
name="Droplet"
damage=5
mana_cost=3
cost=0
desc="A small droplet of water that can help you on your journey."
type="water"
starter=true
diff=1

[ATK.id-atk-0001]
name="Ember"
damage=7
mana_cost=4
cost=0
desc="A strong burning ember with a will to kill."
type="fire"
starter=true
diff=1

[ATK.id-atk-0002]
name="Dirt"
damage=4
mana_cost=2
cost=0
desc="Blinding dirt with passion."
type="earth"
starter=true
diff=1

[ATK.id-atk-0003]
name="Solar Flare"
damage=6
mana_cost=6
cost=0
desc="A flare with a passion for genocide."
type="sun"
starter=true
diff=1

[ATK.id-atk-0004]
name="Instinct"
damage=6
mana_cost=4
cost=0
desc="Instinctual desire to kill and feast."
type="nature"
starter=true
diff=1