[world1]
[world1.1]
"name"="Shattered Joe"
"health"=10
"tokens"=115
"reward"="id-atk-0006"
"xp"=100
"id"=11
"diff"=1
"deck"=[
    "id-atk-0004",
    "id-atk-0002",
    "id-atk-0006",
    "id-wpn-0000"
]
"weak-el"=[
    "fire",
    "sun",
    "nature"
]
"res-el"=[]
"weak-mat"=[
    "blade",
    "blunt"
]
"res-mat"=[]
"crit"=1

[world1.2]
"name"="Copperhead"
"health"=14
"tokens"=122
"reward"="id-atk-0010"
"xp"=200
"id"=12
"diff"=1
"deck"=[
    "id-atk-0009",
    "id-atk-0006",
    "id-atk-0002",
    "id-wpn-0004",
    "id-atk-0010"
]
"weak-el"=[
    "sun",
    "water"
]
"res-el"=[
    "fire"
]
"weak-mat"=[
    "wood"
]
"res-mat"=[]
"crit"=5

[world1.3]
"name"="Head-Basher"
"health"=28
"tokens"=150
"reward"="id-wpn-0002"
"xp"=223
"id"=13
"diff"=1
"deck"=[
    "id-atk-0005",
    "id-atk-0007",
    "id-atk-0010",
    "id-atk-0011",
    "id-wpn-0002",
    "id-wpn-0004",
    "id-amr-0000"
]
"weak-el"=[
    "water",
    "nature"
]
"res-el"=[]
"weak-mat"=[
    "blade"
]
"res-mat"=[
    "blunt",
    "hard"
]
"crit"=4

[world2]

[world3]

[world4]

[world5]

[world6]

[world7]